from unittest import TestCase
from unittest.mock import MagicMock, patch
from ORS.ctl.RegistrationCtl import RegistrationCtl


class TestRegistrationCtlPreload(TestCase):
    """Tests for RegistrationCtl.preload() — verifies gender dropdown data is loaded."""

    def setUp(self):
        self.ctl = RegistrationCtl()
        self.request = MagicMock()

    @patch("ORS.ctl.RegistrationCtl.HtmlUtility")
    def test_preload_includes_gender_list(self, mock_html):
        """preload() must include 'gender_list' with Male and Female options."""
        mock_html.get_list_from_list.return_value = "<select></select>"
        result = self.ctl.preload(self.request)
        self.assertIn("gender_list", result)
        self.assertIn("Male", result["gender_list"])
        self.assertIn("Female", result["gender_list"])

    @patch("ORS.ctl.RegistrationCtl.HtmlUtility")
    def test_preload_includes_gender_select_html(self, mock_html):
        """preload() must include 'gender_select' HTML string generated by HtmlUtility."""
        mock_html.get_list_from_list.return_value = "<select>...</select>"
        result = self.ctl.preload(self.request)
        self.assertIn("gender_select", result)
        mock_html.get_list_from_list.assert_called_once()


class TestRegistrationCtlRequestToForm(TestCase):
    """Tests for RegistrationCtl.request_to_form() — verifies POST data is mapped."""

    def setUp(self):
        self.ctl = RegistrationCtl()

    def test_maps_all_fields(self):
        """All registration fields must be mapped; role_id must always be set to 2."""
        post = {
            "id": "0", "firstName": "Jane", "lastName": "Doe",
            "login": "jane@example.com", "password": "pass123",
            "dob": "2000-01-15", "mobileNumber": "9123456789", "gender": "Female",
        }
        self.ctl.request_to_form(post)
        self.assertEqual(self.ctl.form["firstName"], "Jane")
        self.assertEqual(self.ctl.form["login"], "jane@example.com")
        self.assertEqual(self.ctl.form["role_id"], 2)

    def test_role_id_is_always_2(self):
        """role_id must be hardcoded to 2 regardless of any POST value."""
        self.ctl.request_to_form({})
        self.assertEqual(self.ctl.form["role_id"], 2)


class TestRegistrationCtlModelToForm(TestCase):
    """Tests for RegistrationCtl.model_to_form() — verifies a User instance is reflected in self.form."""

    def setUp(self):
        self.ctl = RegistrationCtl()

    def test_model_to_form_populates_form(self):
        """All User model attributes must be copied into the form."""
        user = MagicMock()
        user.id = 5
        user.firstName = "Jane"
        user.lastName = "Doe"
        user.login = "jane@example.com"
        user.password = "pass"
        user.dob.strftime.return_value = "2000-01-15"
        user.dob = MagicMock()
        user.dob.strftime = MagicMock(return_value="2000-01-15")
        user.mobileNumber = "9123456789"
        user.gender = "Female"
        user.role_id = 2
        self.ctl.model_to_form(user)
        self.assertEqual(self.ctl.form["firstName"], "Jane")
        self.assertEqual(self.ctl.form["role_id"], 2)

    def test_model_to_form_with_none_does_nothing(self):
        """Passing None must leave self.form completely unchanged."""
        original = dict(self.ctl.form)
        self.ctl.model_to_form(None)
        self.assertEqual(self.ctl.form, original)


class TestRegistrationCtlFormToModel(TestCase):
    """Tests for RegistrationCtl.form_to_model() — verifies form data is written onto a User instance."""

    def setUp(self):
        self.ctl = RegistrationCtl()

    def test_form_to_model_with_positive_id(self):
        """When id > 0, pk must be set on the model instance."""
        self.ctl.form.update({
            "id": "3", "firstName": "Jane", "lastName": "Doe",
            "login": "jane@example.com", "password": "pass",
            "dob": "2000-01-15", "mobileNumber": "9123456789", "gender": "Female", "role_id": 2,
        })
        user = MagicMock()
        result = self.ctl.form_to_model(user)
        self.assertEqual(user.id, 3)
        self.assertEqual(user.firstName, "Jane")
        self.assertIs(result, user)

    def test_form_to_model_with_zero_id_skips_pk(self):
        """When id == 0, obj.id must not be assigned so the DB auto-generates it."""
        self.ctl.form.update({
            "id": "0", "firstName": "John", "lastName": "Smith",
            "login": "john@example.com", "password": "pw",
            "dob": "", "mobileNumber": "9000000000", "gender": "Male", "role_id": 2,
        })
        user = MagicMock()
        self.ctl.form_to_model(user)
        # MagicMock attribute assignment is stored directly; verify a real field was set
        self.assertEqual(user.firstName, "John")
        # id must not have been set (explicit pk=0 assignment must not happen)
        self.assertNotEqual(user.id, 0)


class TestRegistrationCtlInputValidation(TestCase):
    """Tests for RegistrationCtl.input_validation() — verifies required-field rules."""

    def setUp(self):
        self.ctl = RegistrationCtl()

    def _fill_valid(self):
        self.ctl.form.update({
            "firstName": "Jane", "lastName": "Doe",
            "login": "jane@example.com", "password": "pass123",
            "mobileNumber": "9876543210",
        })

    def test_valid_form_returns_false(self):
        """A complete valid form must return False."""
        self._fill_valid()
        self.assertFalse(self.ctl.input_validation())

    def test_missing_first_name_sets_error(self):
        """An empty firstName must add 'firstName' to inputError."""
        self._fill_valid()
        self.ctl.form["firstName"] = ""
        self.assertTrue(self.ctl.input_validation())
        self.assertIn("firstName", self.ctl.form["inputError"])

    def test_missing_last_name_sets_error(self):
        """An empty lastName must add 'lastName' to inputError."""
        self._fill_valid()
        self.ctl.form["lastName"] = ""
        self.assertTrue(self.ctl.input_validation())
        self.assertIn("lastName", self.ctl.form["inputError"])

    def test_missing_login_sets_error(self):
        """An empty login must add 'login' to inputError."""
        self._fill_valid()
        self.ctl.form["login"] = ""
        self.assertTrue(self.ctl.input_validation())
        self.assertIn("login", self.ctl.form["inputError"])

    def test_invalid_login_email_sets_error(self):
        """A login that is not a valid email must add 'login' to inputError."""
        self._fill_valid()
        self.ctl.form["login"] = "not-an-email"
        self.assertTrue(self.ctl.input_validation())
        self.assertIn("login", self.ctl.form["inputError"])

    def test_missing_password_sets_error(self):
        """An empty password must add 'password' to inputError."""
        self._fill_valid()
        self.ctl.form["password"] = ""
        self.assertTrue(self.ctl.input_validation())
        self.assertIn("password", self.ctl.form["inputError"])

    def test_missing_mobile_sets_error(self):
        """An empty mobileNumber must add 'mobileNumber' to inputError."""
        self._fill_valid()
        self.ctl.form["mobileNumber"] = ""
        self.assertTrue(self.ctl.input_validation())
        self.assertIn("mobileNumber", self.ctl.form["inputError"])

    def test_invalid_mobile_format_sets_error(self):
        """A non-10-digit mobileNumber must add 'mobileNumber' to inputError."""
        self._fill_valid()
        self.ctl.form["mobileNumber"] = "12345"
        self.assertTrue(self.ctl.input_validation())
        self.assertIn("mobileNumber", self.ctl.form["inputError"])


class TestRegistrationCtlDisplay(TestCase):
    """Tests for RegistrationCtl.display() — verifies conditional data load and render."""

    def setUp(self):
        self.ctl = RegistrationCtl()
        self.request = MagicMock()

    @patch("ORS.ctl.RegistrationCtl.HtmlUtility")
    @patch("ORS.ctl.RegistrationCtl.render")
    def test_display_without_id_skips_service(self, mock_render, mock_html):
        """display() with id == 0 must not call the service."""
        mock_render.return_value = MagicMock()
        mock_html.get_list_from_list.return_value = ""
        self.ctl.get_service = MagicMock()
        self.ctl.display(self.request, params={})
        self.ctl.get_service.assert_not_called()

    @patch("ORS.ctl.RegistrationCtl.HtmlUtility")
    @patch("ORS.ctl.RegistrationCtl.render")
    def test_display_renders_correct_template(self, mock_render, mock_html):
        """display() must render 'ors/Registration.html'."""
        mock_render.return_value = MagicMock()
        mock_html.get_list_from_list.return_value = ""
        self.ctl.display(self.request, params={})
        self.assertEqual(mock_render.call_args[0][1], "ors/Registration.html")


class TestRegistrationCtlSubmit(TestCase):
    """Tests for RegistrationCtl.submit() — verifies signup is called and success message set."""

    def setUp(self):
        self.ctl = RegistrationCtl()
        self.ctl.form.update({
            "id": "0", "firstName": "Jane", "lastName": "Doe",
            "login": "jane@example.com", "password": "pass",
            "dob": "", "mobileNumber": "9876543210", "gender": "Female", "role_id": 2,
        })
        self.request = MagicMock()

    @patch("ORS.ctl.RegistrationCtl.HtmlUtility")
    @patch("ORS.ctl.RegistrationCtl.render")
    @patch("ORS.ctl.RegistrationCtl.User")
    def test_submit_calls_signup(self, mock_user_cls, mock_render, mock_html):
        """submit() must call service.signup() with the constructed User instance."""
        mock_render.return_value = MagicMock()
        mock_html.get_list_from_list.return_value = ""
        user_instance = MagicMock()
        user_instance.id = 10
        mock_user_cls.return_value = user_instance
        mock_service = MagicMock()
        mock_service.signup.return_value = user_instance
        self.ctl.get_service = MagicMock(return_value=mock_service)

        self.ctl.submit(self.request, params={})

        mock_service.signup.assert_called_once()
        self.assertFalse(self.ctl.form["error"])
        self.assertIn("successful", self.ctl.form["message"])


class TestRegistrationCtlMeta(TestCase):
    """Tests for RegistrationCtl.get_template() and get_service()."""

    def setUp(self):
        self.ctl = RegistrationCtl()

    def test_get_template(self):
        """get_template() must return 'ors/Registration.html'."""
        self.assertEqual(self.ctl.get_template(), "ors/Registration.html")

    def test_get_service_returns_user_service(self):
        """get_service() must return a UserService instance."""
        from service.service.UserService import UserService
        self.assertIsInstance(self.ctl.get_service(), UserService)
